### ISSUE TITLE
AttributeError:  'xml.etree.ElementTree.Element' object has no attribute 'getiterator'

### ISSUE THREAD

**Issue by bernie-g** [g-provost/lightgallery-markdown#6]
Hey, I'm trying to get this extension to work with mkdocs, but I'm getting this error: https://gist.github.com/bernie-g/0b5ed39581947437e5d543fe51eb140e

I haven't used python much, any ideas?

**Comment by g-provost** [comment]
@faustefan Can you have a look ?

**Comment by tirkarthi** [comment]
> Methods getchildren() and getiterator() of classes ElementTree and Element in the ElementTree module have been removed. They were deprecated in Python 3.2. Use iter(x) or list(x) instead of x.getchildren() and x.iter() or list(x.iter()) instead of x.getiterator(). (Contributed by Serhiy Storchaka in bpo-36543.)

https://docs.python.org/3.9/whatsnew/3.9.html#removed

I have created #7 to fix this.

**Comment by g-provost** [comment]
Thanks @tirkarthi
