### ISSUE TITLE
How to implement this alongside Material for MkDocs?

### ISSUE THREAD

**Issue by Andre601** [g-provost/lightgallery-markdown#8]
I'm currently struggling on how to get this working with the Material-theme for MkDocs.

I tried my best to setup everything as explained in the Readme, but I'm not sure how I could download this through pip, as I use a GitHub Action to update the pages automatically.
I have a `requirements.txt` which is used for pip, so all I basically need is the name and version to add and possibly some more detailed guide on how to set this up, as the readme, while explaining the setup after installation, doesn't give info on if there are any specific cases for when you want to use it with Material for MkDocs.

**Comment by TRaSH-** [comment]
Add this: `git+git://github.com/g-provost/lightgallery-markdown#egg=lightgallery` to your `requirements.txt`

**Comment by Andre601** [comment]
Anything else like a version or similar?

**Comment by Andre601** [comment]
It seems to work. Thank you!
